name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore

    - name: npm install and build
      run: |
        npm --prefix VuePlanning/ClientApp/ install
        npm --prefix VuePlanning/ClientApp/ run build --if-present
   
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o publish 

    - name: List output files
      run: ls -lR ./publish/

    - name: FTP Deploy
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_URL }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        localDir: "publish"      
